// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AppError = { "code": "not-supported-on-platform" } | { "code": "io", "detail": string } | { "code": "conflict" } | { "code": "decode", "detail": string } | { "code": "internal", "detail": string };
