// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SensorType } from "./SensorType";

export type CameraMeta = { make: string | null, model: string | null, serial: string | null, firmware: string | null, sensorType: SensorType, cfaPattern: string | null, cropFactor: number | null, };
