// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CurvePoint } from "./CurvePoint";

export type CurvesState = { rgb: Array<CurvePoint>, red: Array<CurvePoint>, green: Array<CurvePoint>, blue: Array<CurvePoint>, };
