// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DatesMeta = { original: string | null, digitized: string | null, modified: string | null, timezoneOffset: string | null, subSec: string | null, };
