// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProxyLevel } from "./ProxyLevel";

export type DecodeFailedPayload = { imageId: string, level: ProxyLevel, message: string, };
