// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DistortionModel } from "./DistortionModel";

export type DistortionCoeffs = { model: DistortionModel, coeffs: Array<number>, };
