// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DrawerLayer } from "./DrawerLayer";

export type DrawerState = { layers: Array<DrawerLayer>, };
