// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EditState } from "./EditState";

export type EditStateEnvelope = { state: EditState, editVersion: number, isDefault: boolean, };
