// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DepthOfField } from "./DepthOfField";
import type { FlashInfo } from "./FlashInfo";
import type { ShutterSpeed } from "./ShutterSpeed";

export type ExposureMeta = { shutterSpeed: ShutterSpeed | null, fNumber: number | null, iso: number | null, focalLength: number | null, exposureBias: number | null, exposureMode: string | null, meteringMode: string | null, flash: FlashInfo | null, whiteBalance: string | null, wbTemp: number | null, subjectDistance: number | null, dof: DepthOfField | null, driveMode: string | null, stabilization: string | null, };
