// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExportPhase } from "./ExportPhase";

export type ExportProgressPayload = { jobId: string, phase: ExportPhase, done: number, total: number, };
