// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FileMeta = { name: string, path: string, sizeBytes: number, format: string, width: number | null, height: number | null, megapixels: number | null, bitDepth: number | null, colorSpace: string | null, iccProfileName: string | null, createdAt: number | null, modifiedAt: number | null, hasSidecar: boolean, };
