// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CameraMeta } from "./CameraMeta";
import type { DatesMeta } from "./DatesMeta";
import type { ExposureMeta } from "./ExposureMeta";
import type { FileMeta } from "./FileMeta";
import type { GpsMeta } from "./GpsMeta";
import type { LensMeta } from "./LensMeta";
import type { MetadataWarning } from "./MetadataWarning";
import type { RawMeta } from "./RawMeta";

export type ImageMetadata = { file: FileMeta, camera: CameraMeta, lens: LensMeta, exposure: ExposureMeta, dates: DatesMeta, gps: GpsMeta | null, raw: RawMeta | null, warnings: Array<MetadataWarning>, };
