// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LensState = { autoProfile: boolean, profileId: string | null, distortion: number, tca: number, vignette: number, manualVignette: number, manualDistortion: number, };
