// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LensMeta = { make: string | null, model: string | null, serial: string | null, mount: string | null, maxAperture: number | null, focalLength35mm: number | null, teleconverter: string | null, };
