// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MetadataWarning = "no-color-profile" | "unsupported-sensor" | "corrupt-exif";
