// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ImageEntry } from "./ImageEntry";

export type OpenResult = { entry: ImageEntry, dir: string, };
