// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Flag } from "./Flag";

export type OrganizeEntry = { imageId: string, rating: number, flag: Flag | null, label: string | null, };
