// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { L2Policy } from "./L2Policy";

export type PerfSettings = { preloadRadius: number, l2Policy: L2Policy, isolatedDecode: boolean, };
