// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PresetSource } from "./PresetSource";

export type PresetInfo = { id: string, name: string, folder: string, fieldMask: Array<string>, source: PresetSource, builtin: boolean, createdAt: number, };
