// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConflictPolicy } from "./ConflictPolicy";
import type { ExportColorSpace } from "./ExportColorSpace";
import type { ExportMetadata } from "./ExportMetadata";
import type { OutputSharpen } from "./OutputSharpen";
import type { RasterFormat } from "./RasterFormat";
import type { ResizeSpec } from "./ResizeSpec";

export type RasterExportRequest = { imageId: string, format: RasterFormat, quality: number, colorSpace: ExportColorSpace, bits: number, resize: ResizeSpec, sharpen: OutputSharpen, metadata: ExportMetadata, filenameTemplate: string, outputDir: string, conflict: ConflictPolicy, sourceWidth: number, sourceHeight: number, seq: number, presetName: string | null, };
