// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EmbeddedPreview } from "./EmbeddedPreview";

export type RawMeta = { isDng: boolean, dngVersion: string | null, blackLevel: Array<number>, whiteLevel: Array<number>, asShotNeutral: Array<number> | null, hasColorMatrix: boolean, compression: string | null, embeddedPreviews: Array<EmbeddedPreview>, hasOpcodeList: boolean, };
