// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ImageEntry } from "./ImageEntry";

export type ScanBatch = { entries: Array<ImageEntry>, done: boolean, };
