// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TcaModel } from "./TcaModel";

export type TcaCoeffs = { model: TcaModel, coeffs: Array<number>, };
