// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ToneState = { exposure: number, contrast: number, highlights: number, shadows: number, whites: number, blacks: number, highlightRecovery: number, };
