// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WbMode = "as-shot" | "auto" | "custom" | "daylight" | "cloudy" | "shade" | "tungsten" | "fluorescent" | "flash";
