// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WbMode } from "./WbMode";

export type WbState = { mode: WbMode, temp: number, tint: number, tempShift: number | null, };
